In [2]:
import numpy as np

minhaLista = [3, 5, 7, 9]
meuArray = np.array(minhaLista)
print(meuArray/2)


[1.5 2.5 3.5 4.5]


In [3]:
import numpy as np

dados = [3, 5, 7, 9]
array = np.array(dados)
print("dados")
print(dados)
print("array")
print(array)
arranjo = np.arange(10)
print("arranjo")
print(arranjo)
uns = np.ones((2, 2))
print("uns")
print(uns)
zeros = np.zeros(10)
print("zeros")
print(zeros)
zeros2 = np.zeros((2, 3))
print("zeros2")
print(zeros2)
vazios = np.empty((2, 3))
print("vazios")
print(vazios)


dados
[3, 5, 7, 9]
array
[3 5 7 9]
arranjo
[0 1 2 3 4 5 6 7 8 9]
uns
[[1. 1.]
 [1. 1.]]
zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
zeros2
[[0. 0. 0.]
 [0. 0. 0.]]
vazios
[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
print("array1")
print(a1)
a2 = np.ones((2, 3))
print("a2")
print(a2)
print("a1+a2")
print(a1 + a2)
print("a1 * 2")
print(a1 * 2)
print("a1 ^ 2")
print(a1 ** 2)
print("a1 - a1")
print(a1 - a1)


array1
[[1 2 3]
 [4 5 6]]
a2
[[1. 1. 1.]
 [1. 1. 1.]]
a1+a2
[[2. 3. 4.]
 [5. 6. 7.]]
a1 * 2
[[ 2  4  6]
 [ 8 10 12]]
a1 ^ 2
[[ 1  4  9]
 [16 25 36]]
a1 - a1
[[0 0 0]
 [0 0 0]]


In [6]:
# outras operacoes com array

minhaLista = [3, 4, 5, 7]
meuArray = np.array(minhaLista)
print(meuArray)
pedacoArray = meuArray[1:3]
print("parte do array")
print(pedacoArray)
print("modificando parte do array")
pedacoArray[1] = 23
print(pedacoArray)
print("voltando ao array original")
print(minhaLista)


[3 4 5 7]
parte do array
[4 5]
modificando parte do array
[ 4 23]
voltando ao array original
[3, 4, 5, 7]


In [7]:
# arrays de 3 dimensoes

array3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])

print(array3d)
print("primeiro array")
print(array3d[0])
print("copiando os dados do primeiro array")
old_values = array3d[0].copy()
print(old_values)
print("mudando o valor do primeiro array")
array3d[0] = 25
print(array3d[0])
print("voltando o valor do primeiro array")
array3d[0] = old_values
print(array3d[0])


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
primeiro array
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
copiando os dados do primeiro array
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
mudando o valor do primeiro array
[[25 25 25]
 [25 25 25]
 [25 25 25]
 [25 25 25]]
voltando o valor do primeiro array
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
